### ISSUE TITLE
Suggestion: Implement URI handler

### ISSUE THREAD

**Issue by Cronium** [sjp/GOMstreamer#22]
Bit of a "possible future" but I think one day it would be nice to implement a URI handler so that we can simply click on the link, similar to how GOMplayer works. This would also remove most of the UI, leaving only the VLC location and possible scheduled play.

**Comment by sjp** [comment]
I assume this is for the Windows .NET client.

It is certainly worth looking into, the only issue I forsee is with user credentials. I think what we could do is simply launch GOMstreamer when clicking on a gomp2p link. It would be a little inconvenient not having it be an automatic process but I guess it wouldn't be too bad.

**Comment by Cronium** [comment]
It would probably work for this python client as well, through it would require the writing of some code to parse the URI.

**Comment by joequery** [comment]
Would a browser extension provide the necessary access to do this?

**Comment by sjp** [comment]
@Cronium We can probably reasonably support GNOME, KDE, OSX and Windows. Also had a look into the gomp2p link. The GOX XML file it links to knows about the user via a hash of a member ID in a GET parameter. This is why the GOX XML file does not check for cookies (because the GOM Player wouldn't have the cookies either).

We can simplify the process a lot by simply parsing the linked GOX XML file that we end up getting anyway. Looks like we can certainly get this done easily as we've already all the code to do this. All we really need to do is write some scripts to register URI handlers. I'll have a go at implementing this.

@joequery As I've noticed above, we won't need a browser extension to do this.
