### ISSUE TITLE
Scheduled play not working correctly.

### ISSUE THREAD

**Issue by glh5** [sjp/GOMstreamer#26]
Scheduled playback function does not currently work for me. This is the traceback:

`arjen@arjen-desktop:~$ Desktop/GOMstreamer/Shell\ script/scheduled-play.sh 
Traceback (most recent call last):
  File "/home/arjen/Desktop/GOMstreamer/gomstreamer.py", line 488, in <module>
    main()
  File "/home/arjen/Desktop/GOMstreamer/gomstreamer.py", line 78, in main
    delay(options.kt)
  File "/home/arjen/Desktop/GOMstreamer/gomstreamer.py", line 365, in delay
    record_delta = (target_korean_time - current_korean_time).total_seconds()
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'
arjen@arjen-desktop:~$`

I used the default value (18:00).

**Comment by sjp** [comment]
You need Python 2.7 or greater for this to run. To see what version of Python you're running, execute `python --version`.

If you're running one of the Debian derivatives you should be able to install 2.7 by running `apt-get install python2.7`. You might need to modify your *.sh scripts so that they call `python2.7` rather than `python`.
